"""Campo documento para usuario

Revision ID: 278a5dd8c026
Revises: 87f7e0f17fbd
Create Date: 2026-05-31 17:38:19.579367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278a5dd8c026'
down_revision: Union[str, None] = '87f7e0f17fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('documento', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'documento')
    # ### end Alembic commands ###
