"""cambio grado y grupo a str

Revision ID: 8438a9245df3
Revises: 278a5dd8c026
Create Date: 2026-06-01 13:31:29.752266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8438a9245df3'
down_revision: Union[str, None] = '278a5dd8c026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salon', 'grado',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('salon', 'grupo',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salon', 'grupo',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)
    op.alter_column('salon', 'grado',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
