"""fix: error de brayan

Revision ID: a8ce7a091c9f
Revises: ff8b46cf1938
Create Date: 2026-06-11 13:29:00.196736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ce7a091c9f'
down_revision: Union[str, None] = 'ff8b46cf1938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventario_instrumento', sa.Column('cantidad_total', sa.Integer(), nullable=False))
    op.add_column('inventario_instrumento', sa.Column('cantidad_disponible', sa.Integer(), nullable=False))
    op.add_column('inventario_instrumento', sa.Column('estado', sa.String(length=50), nullable=False))
    op.drop_column('inventario_instrumento', 'disponible')
    op.add_column('prestamo_instrumento', sa.Column('estado_al_devolver', sa.String(length=50), nullable=True))
    op.alter_column('responsable_firma', 'id_tipo_firma',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responsable_firma', 'id_tipo_firma',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('prestamo_instrumento', 'estado_al_devolver')
    op.add_column('inventario_instrumento', sa.Column('disponible', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('inventario_instrumento', 'estado')
    op.drop_column('inventario_instrumento', 'cantidad_disponible')
    op.drop_column('inventario_instrumento', 'cantidad_total')
    # ### end Alembic commands ###
