"""path por firmas y campos faltantes

Revision ID: aef06b351c56
Revises: b023178abd10
Create Date: 2026-05-16 12:11:44.840558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef06b351c56'
down_revision: Union[str, None] = 'b023178abd10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dir_firmas',
    sa.Column('id_dir_firma', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('dir_user', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_dir_firma')
    )
    op.create_index(op.f('ix_dir_firmas_id_dir_firma'), 'dir_firmas', ['id_dir_firma'], unique=False)
    op.add_column('detalle_matricula', sa.Column('mes', sa.String(length=12), nullable=True))
    op.drop_column('detalle_matricula', 'descripcion')
    op.add_column('firmas_paz_y_salvo', sa.Column('prueba', sa.Boolean(), nullable=True))
    op.add_column('firmas_paz_y_salvo', sa.Column('pupitre', sa.Boolean(), nullable=True))
    op.add_column('firmas_paz_y_salvo', sa.Column('inventario', sa.Boolean(), nullable=True))
    op.drop_column('firmas_paz_y_salvo', 'salon')
    op.add_column('periodo_academico', sa.Column('fecha_inicio', sa.TIMESTAMP(), nullable=False))
    op.add_column('periodo_academico', sa.Column('fecha_fin', sa.TIMESTAMP(), nullable=False))
    op.alter_column('periodo_academico', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=4),
               existing_nullable=False)
    op.drop_column('periodo_academico', 'anio')
    op.add_column('usuario', sa.Column('estado', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'estado')
    op.add_column('periodo_academico', sa.Column('anio', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('periodo_academico', 'nombre',
               existing_type=sa.String(length=4),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('periodo_academico', 'fecha_fin')
    op.drop_column('periodo_academico', 'fecha_inicio')
    op.add_column('firmas_paz_y_salvo', sa.Column('salon', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('firmas_paz_y_salvo', 'inventario')
    op.drop_column('firmas_paz_y_salvo', 'pupitre')
    op.drop_column('firmas_paz_y_salvo', 'prueba')
    op.add_column('detalle_matricula', sa.Column('descripcion', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('detalle_matricula', 'mes')
    op.drop_index(op.f('ix_dir_firmas_id_dir_firma'), table_name='dir_firmas')
    op.drop_table('dir_firmas')
    # ### end Alembic commands ###
