"""remove_ubicacion_banda

Revision ID: cc29ff7a61ed
Revises: a8ce7a091c9f
Create Date: 2026-06-14 02:27:57.653920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc29ff7a61ed'
down_revision: Union[str, None] = 'a8ce7a091c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventario_instrumento_id_ubicacion_fkey', 'inventario_instrumento', type_='foreignkey')
    op.drop_column('inventario_instrumento', 'id_ubicacion')
    op.drop_index('ix_ubicacion_id_ubicacion', table_name='ubicacion')
    op.drop_table('ubicacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventario_instrumento', sa.Column('id_ubicacion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('inventario_instrumento_id_ubicacion_fkey', 'inventario_instrumento', 'ubicacion', ['id_ubicacion'], ['id_ubicacion'])
    op.create_table('ubicacion',
    sa.Column('id_ubicacion', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_ubicacion', name='ubicacion_pkey')
    )
    op.create_index('ix_ubicacion_id_ubicacion', 'ubicacion', ['id_ubicacion'], unique=False)
    # ### end Alembic commands ###
