"""fix: error de cristian leal robot

Revision ID: ce56bf29e0b4
Revises: d3f0306084fa
Create Date: 2026-06-07 17:40:06.737513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce56bf29e0b4'
down_revision: Union[str, None] = 'd3f0306084fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejecuciones_bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_fin', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('registros_estudiantes', sa.Integer(), nullable=True),
    sa.Column('registros_docentes', sa.Integer(), nullable=True),
    sa.Column('errores', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo_ejecucion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ejecuciones_bot_id'), 'ejecuciones_bot', ['id'], unique=False)
    op.create_table('staging_docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejecucion_id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('grado_titular', sa.String(length=100), nullable=True),
    sa.Column('curso_titular', sa.String(length=100), nullable=True),
    sa.Column('estado_validacion', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('fecha_carga', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ejecucion_id'], ['ejecuciones_bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_docentes_documento'), 'staging_docentes', ['documento'], unique=False)
    op.create_index(op.f('ix_staging_docentes_id'), 'staging_docentes', ['id'], unique=False)
    op.create_table('staging_estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejecucion_id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('grado', sa.String(length=100), nullable=True),
    sa.Column('curso', sa.String(length=100), nullable=True),
    sa.Column('jornada', sa.String(length=100), nullable=True),
    sa.Column('estado_validacion', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('fecha_carga', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_salon', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ejecucion_id'], ['ejecuciones_bot.id'], ),
    sa.ForeignKeyConstraint(['id_salon'], ['salon.id_salon'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_estudiantes_documento'), 'staging_estudiantes', ['documento'], unique=False)
    op.create_index(op.f('ix_staging_estudiantes_id'), 'staging_estudiantes', ['id'], unique=False)
    op.alter_column('inventario_objeto', 'tipo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('inventario_objeto', 'observacion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_inventario_objeto_id_objeto', table_name='inventario_objeto')
    op.alter_column('prestamo_objeto', 'id_objeto',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prestamo_objeto', 'id_estudiante',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prestamo_objeto', 'fecha_prestamo',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('prestamo_objeto', 'fecha_devolucion',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('prestamo_objeto', 'observacion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prestamo_objeto', 'observacion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('prestamo_objeto', 'fecha_devolucion',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('prestamo_objeto', 'fecha_prestamo',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('prestamo_objeto', 'id_estudiante',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('prestamo_objeto', 'id_objeto',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_inventario_objeto_id_objeto', 'inventario_objeto', ['id_objeto'], unique=False)
    op.alter_column('inventario_objeto', 'observacion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('inventario_objeto', 'tipo',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_staging_estudiantes_id'), table_name='staging_estudiantes')
    op.drop_index(op.f('ix_staging_estudiantes_documento'), table_name='staging_estudiantes')
    op.drop_table('staging_estudiantes')
    op.drop_index(op.f('ix_staging_docentes_id'), table_name='staging_docentes')
    op.drop_index(op.f('ix_staging_docentes_documento'), table_name='staging_docentes')
    op.drop_table('staging_docentes')
    op.drop_index(op.f('ix_ejecuciones_bot_id'), table_name='ejecuciones_bot')
    op.drop_table('ejecuciones_bot')
    # ### end Alembic commands ###
