"""add_id_tipo_firma_to_responsable_firma

Revision ID: ff8b46cf1938
Revises: ce56bf29e0b4
Create Date: 2026-06-09 16:07:23.246259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8b46cf1938'
down_revision: Union[str, None] = 'ce56bf29e0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responsable_firma', sa.Column('id_tipo_firma', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'responsable_firma', 'tipo_firma', ['id_tipo_firma'], ['id_tipo_firma'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responsable_firma', type_='foreignkey')
    op.drop_column('responsable_firma', 'id_tipo_firma')
    # ### end Alembic commands ###
